# Generated by Django 5.1.6 on 2025-02-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='SKU INDENTIFIER', max_length=100, unique=True),
        ),
    ]
