# Generated by Django 5.2 on 2025-05-03 19:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descriptions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
