# Generated by Django 5.1.6 on 2025-02-28 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time of record creation (automatically).', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time of soft deletion (automatically).', null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(help_text='Brand logo image.', upload_to='brands/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'bmp', 'tiff'])], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique identifier in the URL.', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.BooleanField(default=True, help_text='Brand visibility status.', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time of the last update (automatically).', verbose_name='Updated At'),
        ),
    ]
