# Generated by Django 5.1.6 on 2025-03-01 21:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_category_created_at_alter_category_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, help_text='Brand logo image. Accepted formats: JPG, JPEG, PNG, SVG, GIF, WEBP, BMP, TIFF.', null=True, upload_to='brands/logo/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'bmp', 'tiff'])], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(help_text='Brand name.', max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly unique identifier.', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Category logo image. Accepted formats: JPG, JPEG, PNG, SVG, GIF, WEBP, BMP, TIFF.', null=True, upload_to='category/image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'bmp', 'tiff'])], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly unique identifier.', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(help_text='The brand this product belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='The category this product belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time of record creation (automatically).', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time of soft deletion (automatically).', null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Detailed product description.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The discount percentage (0.00 to 100.00).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image. Accepted formats: JPG, JPEG, PNG, SVG, GIF, WEBP, BMP, TIFF.', null=True, upload_to='products/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'bmp', 'tiff'])], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Product name.', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='The price of the product.', max_digits=12, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=1, help_text='The product rating from 1 to 5 stars.', verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Unique SKU identifier for the product.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly unique identifier.', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True, help_text='Product visibility status.', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='The number of items available in stock.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time of the last update (automatically).', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.CharField(blank=True, help_text='Business address.', max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time of record creation (automatically).', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time of soft deletion (automatically).', null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address.', max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='facebook',
            field=models.URLField(blank=True, help_text='Link to the Facebook page.', null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='instagram',
            field=models.URLField(blank=True, help_text='Link to the Instagram page.', null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Link to the LinkedIn profile.', null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Turns on/off maintenance mode.', verbose_name='Maintenance Mode'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number.', max_length=24, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='snow_mode',
            field=models.BooleanField(default=False, help_text='Turns on/off snow effect.', verbose_name='Snow Mode'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='twitter',
            field=models.URLField(blank=True, help_text='Link to the Twitter profile.', null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time of the last update (automatically).', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='working_time',
            field=models.TextField(blank=True, help_text='Business working hours.', null=True, verbose_name='Working Time'),
        ),
    ]
