# Generated by Django 5.1.6 on 2025-02-23 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_product_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('-created_at',), 'verbose_name': 'xBrand', 'verbose_name_plural': 'Brands'},
        ),
    ]
