# Generated by Django 5.1.6 on 2025-02-23 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_brand_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('-created_at',), 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
    ]
