# Generated by Django 5.1.6 on 2025-02-23 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_brand_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='contact_phone',
            new_name='phone',
        ),
    ]
