# Generated by Django 5.1.6 on 2025-02-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_rename_contact_phone_setting_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='Maintenance Mode'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Phone'),
        ),
    ]
